### ISSUE TITLE
Possible to make breakable?

### ISSUE THREAD

**Issue by LostNMemes** [isaaclepes/LucidLightBlocks#2]
Basically the title, is there a way to make the block breakable while in survival is that possible?

**Comment by isaaclepes** [comment]
Not without a mod/plugin/mcfunction for it, because of the way the light blocks are designed. You can place another block where the light block is to remove it.  The intent of this datapack is just to add recipes, but maybe an implementation like Bottle O' Light might suit your needs better.  https://www.planetminecraft.com/data-pack/bottle-o-light/
